import { StockItem, ToolItem, MachinePartItem } from './types';

export const INITIAL_STOCK: StockItem[] = [
  {
    id: 'stk-001',
    sku: 'AL-6061-RD-2.000',
    name: '6061-T6 Aluminum Round Bar',
    category: 'aluminum',
    alloyGrade: '6061-T6',
    shape: 'round-bar',
    diameter: 2.0,
    length: 72,
    unit: 'in',
    fullStockQty: 5,
    minThreshold: 2,
    offcuts: [
      { id: 'oc-1', length: 14.5, quantity: 2, location: 'Bin A-1-Drop', jobRef: 'JOB-412', dateCreated: '2026-08-20' },
      { id: 'oc-2', length: 8.25, quantity: 1, location: 'Bin A-1-Drop', jobRef: 'JOB-415', dateCreated: '2026-08-22' }
    ],
    rackLocation: 'Cantilever Rack A - Bay 1',
    status: 'in-stock',
    heatNumber: 'HT-88491-AL',
    supplier: 'Alro Metals',
    costPerUnit: 64.50,
    allocatedJob: '',
    lastUpdated: '2026-08-24',
    notes: 'Primary turning stock for CNC lathe lathe chucks.'
  },
  {
    id: 'stk-002',
    sku: 'AL-6061-FLAT-0.500x2.000',
    name: '6061-T6 Aluminum Flat Bar 1/2" x 2"',
    category: 'aluminum',
    alloyGrade: '6061-T6',
    shape: 'flat-bar',
    width: 2.0,
    thickness: 0.5,
    length: 96,
    unit: 'in',
    fullStockQty: 8,
    minThreshold: 3,
    offcuts: [
      { id: 'oc-3', length: 18.0, quantity: 3, location: 'Shelf B-2', jobRef: 'Fixture Plates', dateCreated: '2026-08-18' }
    ],
    rackLocation: 'Vertical Rack 2 - Slot 4',
    status: 'in-stock',
    heatNumber: 'HT-99201',
    supplier: 'Ryerson',
    costPerUnit: 38.20,
    allocatedJob: '',
    lastUpdated: '2026-08-21',
    notes: 'Great for mill soft jaws and mounting brackets.'
  },
  {
    id: 'stk-003',
    sku: 'ST-1018-RD-1.250',
    name: '1018 Cold Rolled Steel Round Bar',
    category: 'carbon-steel',
    alloyGrade: '1018 Cold Rolled',
    shape: 'round-bar',
    diameter: 1.25,
    length: 144,
    unit: 'in',
    fullStockQty: 1,
    minThreshold: 3,
    offcuts: [
      { id: 'oc-4', length: 22.0, quantity: 1, location: 'Drop Bin 3', jobRef: 'JOB-398', dateCreated: '2026-08-15' }
    ],
    rackLocation: 'Cantilever Rack B - Bay 2',
    status: 'low-stock',
    heatNumber: 'HT-1018-774A',
    supplier: 'OnlineMetals',
    costPerUnit: 52.00,
    allocatedJob: 'JOB-501 (Shafts)',
    lastUpdated: '2026-08-25',
    notes: 'Low stock warning! Need to reorder for September production run.'
  },
  {
    id: 'stk-004',
    sku: 'ST-4140-RD-3.000-HT',
    name: '4140 Chromoly Pre-Hardened Round Bar (28-32 HRC)',
    category: 'alloy-steel',
    alloyGrade: '4140 HT (4140 PH)',
    shape: 'round-bar',
    diameter: 3.0,
    length: 72,
    unit: 'in',
    fullStockQty: 3,
    minThreshold: 1,
    offcuts: [
      { id: 'oc-5', length: 11.5, quantity: 1, location: 'Heavy Bin H-1', jobRef: 'Spindle Shaft', dateCreated: '2026-08-10' }
    ],
    rackLocation: 'Heavy Rack C - Bay 1',
    status: 'in-stock',
    heatNumber: 'MTR-4140-5592',
    supplier: 'Alro Metals',
    costPerUnit: 145.00,
    allocatedJob: '',
    lastUpdated: '2026-08-19',
    notes: 'Pre-heat-treated 4140. Use carbide inserts with 0.015 IPR feed.'
  },
  {
    id: 'stk-005',
    sku: 'SS-304-RD-0.750',
    name: '304 Stainless Steel Round Bar 3/4"',
    category: 'stainless',
    alloyGrade: '304 Stainless',
    shape: 'round-bar',
    diameter: 0.75,
    length: 144,
    unit: 'in',
    fullStockQty: 6,
    minThreshold: 2,
    offcuts: [
      { id: 'oc-6', length: 16.0, quantity: 1, location: 'Stainless Tube Rack', jobRef: 'Food Grade Pins', dateCreated: '2026-08-23' }
    ],
    rackLocation: 'Stainless Bay S-2',
    status: 'in-stock',
    heatNumber: 'HEAT-SS304-411',
    supplier: 'McMaster-Carr',
    costPerUnit: 44.10,
    allocatedJob: '',
    lastUpdated: '2026-08-22',
    notes: 'Keep away from carbon steel to prevent galvanic cross-contamination.'
  },
  {
    id: 'stk-006',
    sku: 'BR-360-HEX-1.000',
    name: '360 Free-Cutting Brass Hex Bar 1.0"',
    category: 'brass-bronze',
    alloyGrade: '360 Brass CDA 360',
    shape: 'hex-bar',
    diameter: 1.0,
    length: 72,
    unit: 'in',
    fullStockQty: 4,
    minThreshold: 2,
    offcuts: [
      { id: 'oc-7', length: 9.0, quantity: 2, location: 'Brass Bin B-1', jobRef: 'Fitting Hex Plugs', dateCreated: '2026-08-17' }
    ],
    rackLocation: 'Crib Rack 4 - Shelf 1',
    status: 'in-stock',
    heatNumber: 'BR-360-901',
    supplier: 'OnlineMetals',
    costPerUnit: 78.00,
    allocatedJob: '',
    lastUpdated: '2026-08-20',
    notes: 'Fast machinability 100% rating. Excellent for threaded brass connectors.'
  },
  {
    id: 'stk-007',
    sku: 'PL-DELRIN-RD-1.500',
    name: 'Delrin / Acetal Black Engineering Polymer Round Rod',
    category: 'plastics',
    alloyGrade: 'Delrin (Acetal POM-H)',
    shape: 'round-bar',
    diameter: 1.5,
    length: 96,
    unit: 'in',
    fullStockQty: 7,
    minThreshold: 2,
    offcuts: [
      { id: 'oc-8', length: 12.0, quantity: 4, location: 'Plastic Drawer P-1', jobRef: 'Insulator Bushings', dateCreated: '2026-08-14' }
    ],
    rackLocation: 'Plastics Rack - Slot 3',
    status: 'in-stock',
    heatNumber: 'PL-LOT-2026-A',
    supplier: 'McMaster-Carr',
    costPerUnit: 32.50,
    allocatedJob: '',
    lastUpdated: '2026-08-23',
    notes: 'Sharp polished HSS or uncoated carbide tooling recommended.'
  }
];

export const INITIAL_TOOLS: ToolItem[] = [
  {
    id: 'tool-001',
    sku: 'EM-CAR-0.500-4F-ALTIN',
    name: '1/2" 4-Flute Variable Helix Solid Carbide End Mill',
    category: 'end-mill',
    toolType: 'Square End Mill',
    sizeDiameter: '0.500"',
    flutes: '4-Flute Variable',
    coating: 'AlTiN / nACo',
    shankOrHolder: '1/2" Weldon / ER32',
    insertGrade: 'Micrograin Carbide 10% Co',
    location: 'Crib Drawer 2A - Milling',
    qtyInStock: 8,
    minThreshold: 3,
    costPerUnit: 48.50,
    condition: 'new',
    supplier: 'Harvey Tool / YG-1',
    assignedMachine: 'Haas VF-2 CNC Mill',
    lastUpdated: '2026-08-25',
    notes: 'Primary rougher & finisher for steel and stainless.'
  },
  {
    id: 'tool-002',
    sku: 'EM-ALUM-0.500-3F-DLC',
    name: '1/2" 3-Flute High-Helix Aluminum End Mill 45°',
    category: 'end-mill',
    toolType: 'Aluminum Rougher/Finisher',
    sizeDiameter: '0.500"',
    flutes: '3-Flute 45° Helix',
    coating: 'ZrN / Polished Flute',
    shankOrHolder: '1/2" Shank',
    insertGrade: 'Sub-micron Carbide',
    location: 'Crib Drawer 2B - Aluminum',
    qtyInStock: 12,
    minThreshold: 4,
    costPerUnit: 39.00,
    condition: 'new',
    supplier: 'Helical Solutions',
    assignedMachine: 'Haas VF-2 CNC Mill',
    lastUpdated: '2026-08-24',
    notes: 'Max 10,000 RPM, 180 IPM in 6061 slotting.'
  },
  {
    id: 'tool-003',
    sku: 'FM-INDEX-2.000-APKT',
    name: '2.00" 45° 5-Insert Indexable Face Mill',
    category: 'face-mill',
    toolType: 'Indexable Face Mill Body',
    sizeDiameter: '2.00" Face (5 Flutes)',
    flutes: '5-Insert Pockets',
    coating: 'Black Oxide Hardened',
    shankOrHolder: 'CAT40 Arbor 3/4" Pilot',
    insertGrade: 'Uses APKT 1604 Inserts',
    location: 'Crib Shelf 1 - Tooling Heads',
    qtyInStock: 2,
    minThreshold: 1,
    costPerUnit: 185.00,
    condition: 'in-machine',
    supplier: 'Korloy / Shars',
    assignedMachine: 'Haas VF-2 Pod 1',
    lastUpdated: '2026-08-22',
    notes: 'Mounted in Haas tool changer pocket #1.'
  },
  {
    id: 'tool-004',
    sku: 'INS-WNMG-432-PM',
    name: 'WNMG 432-PM Double-Sided Carbide Turning Inserts (Box of 10)',
    category: 'carbide-insert',
    toolType: 'Turning Insert (80° Trigon)',
    sizeDiameter: 'WNMG 432 (1/2" IC, 1/32" R)',
    flutes: '6 Cutting Edges',
    coating: 'CVD TiCN + Al2O3 + TiN',
    shankOrHolder: 'MWLNR 16-4D Holder',
    insertGrade: 'GC4325 (Sandvik Steel Grade)',
    location: 'Crib Drawer 1C - Lathe Inserts',
    qtyInStock: 4, // 4 boxes
    minThreshold: 2,
    costPerUnit: 68.00,
    condition: 'new',
    supplier: 'Sandvik Coromant',
    assignedMachine: 'Mazak Quick Turn Lathe',
    lastUpdated: '2026-08-23',
    notes: 'Workhorse turning insert for alloy and carbon steels.'
  },
  {
    id: 'tool-005',
    sku: 'TAP-1/4-20-SPIRAL-FLUTE',
    name: '1/4"-20 UNC HSS-E Spiral Flute Machine Tap',
    category: 'tap-thread',
    toolType: 'Blind Hole Spiral Tap',
    sizeDiameter: '1/4"-20 UNC',
    flutes: '3-Flute Spiral',
    coating: 'TiN Gold Coated',
    shankOrHolder: 'Standard Tap Square Shank',
    insertGrade: 'HSS-Co5',
    location: 'Crib Drawer 4A - Taps & Threading',
    qtyInStock: 6,
    minThreshold: 3,
    costPerUnit: 16.50,
    condition: 'new',
    supplier: 'OSG / Guhring',
    assignedMachine: 'Bridgeport & CNC Mill',
    lastUpdated: '2026-08-25',
    notes: 'For blind holes up to 2.5xD depth.'
  },
  {
    id: 'tool-006',
    sku: 'HLD-CAT40-ER32-70MM',
    name: 'CAT40 to ER32 Precision Collet Chuck Holder (0.0001" TIR)',
    category: 'tool-holder',
    toolType: 'Collet Chuck Tool Holder',
    sizeDiameter: 'ER32 Collet Range (1/16" - 3/4")',
    flutes: 'Balanced G2.5 @ 20,000 RPM',
    coating: 'Precision Ground & Hardened',
    shankOrHolder: 'CAT40 V-Flange',
    insertGrade: 'Case Hardened Steel',
    location: 'Tooling Cart Rack A',
    qtyInStock: 14,
    minThreshold: 5,
    costPerUnit: 110.00,
    condition: 'new',
    supplier: 'Techniks / Command',
    assignedMachine: 'Haas VF-2 Carousel',
    lastUpdated: '2026-08-21',
    notes: 'Torque ER32 nut to 100 ft-lbs with torque wrench.'
  },
  {
    id: 'tool-007',
    sku: 'DRILL-SET-COBALT-29PC',
    name: '1/16" - 1/2" by 64ths Heavy Duty 135° Split Point M42 Cobalt Drill Index',
    category: 'drill-bit',
    toolType: 'Jobber Drill Bit Set',
    sizeDiameter: '1/16" to 1/2" (29 sizes)',
    flutes: '2-Flute 135° Split Point',
    coating: 'Bronze Oxide Treated',
    shankOrHolder: 'Straight Shank',
    insertGrade: 'M42 8% Cobalt HSS',
    location: 'Tool Crib Bench Top',
    qtyInStock: 2,
    minThreshold: 1,
    costPerUnit: 142.00,
    condition: 'new',
    supplier: 'Chicago-Latrobe',
    assignedMachine: 'Shop Wide Drill Station',
    lastUpdated: '2026-08-18',
    notes: 'Re-sharpen on Darex drill grinder when dull.'
  }
];

export const INITIAL_MACHINE_PARTS: MachinePartItem[] = [
  {
    id: 'part-001',
    partNumber: '93-2144B',
    name: 'Haas VF-2 Spindle Drive Poly-V High-Torque Belt',
    machineName: 'Haas VF-2 CNC Mill',
    category: 'belts-pulleys',
    criticality: 'critical-spare',
    location: 'Maintenance Cabinet M-1, Shelf 2',
    qtyInStock: 2,
    minThreshold: 1,
    costPerUnit: 145.00,
    supplier: 'Haas Factory Outlet',
    oemBrand: 'Gates / Haas OEM',
    lastUpdated: '2026-08-20',
    serviceIntervalNotes: 'Inspect tension every 1,000 spindle hours; replace every 3,000 hrs.'
  },
  {
    id: 'part-002',
    partNumber: 'WW-VF2-XYZ-KIT',
    name: 'Telescopic Way Cover Wiper Seals & Brass Scrapers Kit (X & Y Axes)',
    machineName: 'Haas VF-2 CNC Mill',
    category: 'wipers-seals',
    criticality: 'critical-spare',
    location: 'Maintenance Drawer 3B',
    qtyInStock: 1,
    minThreshold: 1,
    costPerUnit: 180.00,
    supplier: 'KabelSchlepp / Hennig',
    oemBrand: 'Hennig Wiper Profiles',
    lastUpdated: '2026-08-15',
    serviceIntervalNotes: 'Prevents chips from entering linear guide ways and ball screw.'
  },
  {
    id: 'part-003',
    partNumber: 'LUBE-FILT-VACTRA2',
    name: 'Bijur Way Lube In-Line Suction Filter & Check Valve 10 Micron',
    machineName: 'Bridgeport Series 1 Mill',
    category: 'filters-lube',
    criticality: 'standard',
    location: 'Lube Station Bin L-2',
    qtyInStock: 4,
    minThreshold: 2,
    costPerUnit: 24.50,
    supplier: 'Bijur Delimon / McMaster',
    oemBrand: 'Bijur Lubrication',
    lastUpdated: '2026-08-22',
    serviceIntervalNotes: 'Clean or replace every 6 months when refilling Mobil Vactra #2.'
  },
  {
    id: 'part-004',
    partNumber: 'DB-SPRING-BELL-40',
    name: 'CAT40 Spindle Drawbar Belleville Disc Springs Stack (Set of 90)',
    machineName: 'Haas VF-2 CNC Mill',
    category: 'drawbar-spindle',
    criticality: 'critical-spare',
    location: 'Maintenance Drawer 1A - Spindle Kit',
    qtyInStock: 2,
    minThreshold: 1,
    costPerUnit: 215.00,
    supplier: 'Haas Service / Belleville Springs',
    oemBrand: 'Schnorr / Haas',
    lastUpdated: '2026-08-10',
    serviceIntervalNotes: 'Check retention pull force every 6 months (Target > 1,800 lbs).'
  },
  {
    id: 'part-005',
    partNumber: 'SW-PROX-NPN-M12',
    name: 'Inductive Proximity Limit Sensor M12 Shielded NPN N.O.',
    machineName: 'Mazak Quick Turn Lathe',
    category: 'electrical-sensors',
    criticality: 'critical-spare',
    location: 'Maintenance Electrical Bin E-4',
    qtyInStock: 3,
    minThreshold: 1,
    costPerUnit: 42.00,
    supplier: 'AutomationDirect / Omron',
    oemBrand: 'Omron E2E Series',
    lastUpdated: '2026-08-17',
    serviceIntervalNotes: 'Turret home switch & tailstock position sensor.'
  },
  {
    id: 'part-006',
    partNumber: 'NOZ-LOCLINE-1/2-KIT',
    name: '1/2" Loc-Line High Flow Coolant Hose Nozzle & Valve Assortment',
    machineName: 'All CNC Mills & Lathes',
    category: 'coolant-nozzles',
    criticality: 'consumable',
    location: 'Plumbing / Coolant Bin C-1',
    qtyInStock: 5,
    minThreshold: 2,
    costPerUnit: 28.00,
    supplier: 'Loc-Line / McMaster',
    oemBrand: 'Lockwood Products',
    lastUpdated: '2026-08-24',
    serviceIntervalNotes: 'Replace when cracked or unable to hold position under 50 PSI pump.'
  },
  {
    id: 'part-007',
    partNumber: 'BLADE-DOALL-1x156',
    name: '1" x 0.035" x 156" 4/6 TPI Matrix Bi-Metal Horizontal Bandsaw Blade',
    machineName: 'DoALL Horizontal Bandsaw',
    category: 'belts-pulleys',
    criticality: 'critical-spare',
    location: 'Saw Station Wall Rack',
    qtyInStock: 4,
    minThreshold: 2,
    costPerUnit: 46.00,
    supplier: 'Lenox / Starrett',
    oemBrand: 'Lenox Classic Pro Bi-Metal',
    lastUpdated: '2026-08-25',
    serviceIntervalNotes: 'Break-in new blade at 50% feed rate for first 50 sq. in. of cutting.'
  }
];
